export const SITE_CONFIG = {
  name: 'Andrea Musar',
  title: 'Andrea Musar — Personal Trainer Lima, Peru',
  description:
    'Entrenadora personal en Lima, Peru. Planes de entrenamiento online y presencial, suplementacion deportiva y planes nutricionales personalizados.',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://andreamusar.com',
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '51906427238',
  instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL ?? 'https://www.instagram.com/andreamusar',
  tiktok: process.env.NEXT_PUBLIC_TIKTOK_URL ?? 'https://www.tiktok.com/@andreamusar',
  email: 'hola@andreamusar.com',
  location: 'Santa Anita, Lima, Peru',
  businessHours: {
    weekdays: 'Lunes – Viernes: 6:00 am – 9:00 pm',
    saturday: 'Sabado: 7:00 am – 5:00 pm',
    sunday: 'Domingo: Cerrado',
  },
}

export const NAV_LINKS = [
  { label: 'Inicio', href: '/' },
  { label: 'Servicios', href: '/servicios' },
  { label: 'Tienda', href: '/tienda' },
  { label: 'Resultados', href: '/resultados' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contacto', href: '/contacto' },
]

export const PRODUCT_CATEGORIES = [
  { label: 'Todos', value: 'all' },
  { label: 'Proteinas', value: 'proteinas' },
  { label: 'Pre-entreno', value: 'pre-entreno' },
  { label: 'Vitaminas', value: 'vitaminas' },
  { label: 'Accesorios', value: 'accesorios' },
]

export const BLOG_CATEGORIES = [
  { label: 'Todos', value: 'all' },
  { label: 'Entrenamiento', value: 'entrenamiento' },
  { label: 'Nutricion', value: 'nutricion' },
  { label: 'Suplementacion', value: 'suplementacion' },
  { label: 'Rutinas', value: 'rutinas' },
  { label: 'Transformacion', value: 'transformacion' },
  { label: 'Consejos para mujeres', value: 'mujeres' },
]

export const SERVICE_TYPES = {
  ONLINE: 'online',
  PRESENCIAL: 'presencial',
  CHALLENGE: 'challenge',
  NUTRICION: 'nutricion',
} as const

export const WHATSAPP_MESSAGES = {
  general: 'Hola Andrea! Me interesa saber mas sobre tus servicios.',
  coaching: 'Hola Andrea! Me interesa el plan de coaching online.',
  presencial: 'Hola Andrea! Me interesa el entrenamiento presencial.',
  tienda: 'Hola Andrea! Quiero hacer un pedido de suplementos.',
  challenge: 'Hola Andrea! Me interesa el reto de fitness.',
}

export const MOCK_SERVICES = [
  {
    id: '1',
    name: 'Plan Basic Online',
    type: 'online',
    price: 99,
    currency: 'USD',
    duration: '1 mes',
    support_level: 'Soporte por WhatsApp (lun-vie)',
    description: 'Ideal para comenzar tu transformacion con guia profesional desde casa.',
    includes: [
      'Plan de entrenamiento personalizado',
      'Seguimiento semanal',
      'Acceso a videos explicativos',
      'Soporte por WhatsApp de lunes a viernes',
    ],
    popular: false,
    active: true,
  },
  {
    id: '2',
    name: 'Plan Standard Online',
    type: 'online',
    price: 159,
    currency: 'USD',
    duration: '1 mes',
    support_level: 'Soporte ilimitado por WhatsApp',
    description: 'Para quienes buscan resultados serios con acompanamiento constante.',
    includes: [
      'Plan de entrenamiento personalizado',
      'Plan nutricional basico',
      'Seguimiento bisemanal',
      'Acceso a videos y biblioteca de ejercicios',
      'Soporte ilimitado por WhatsApp',
      'Ajustes mensuales del plan',
    ],
    popular: true,
    active: true,
  },
  {
    id: '3',
    name: 'Plan Premium Online',
    type: 'online',
    price: 229,
    currency: 'USD',
    duration: '1 mes',
    support_level: 'Soporte 24/7 prioritario',
    description: 'La experiencia completa de coaching fitness y nutricional de elite.',
    includes: [
      'Plan de entrenamiento 100% personalizado',
      'Plan nutricional completo y personalizado',
      'Video llamada semanal de seguimiento',
      'Seguimiento diario de progreso',
      'Soporte 24/7 prioritario',
      'Acceso a todo el contenido premium',
      'Analisis de composicion corporal',
      'Reajustes quincenales de plan',
    ],
    popular: false,
    active: true,
  },
  {
    id: '4',
    name: 'Entrenamiento Presencial',
    type: 'presencial',
    price: 200,
    currency: 'PEN',
    duration: '4 sesiones / mes',
    support_level: 'Presencial en Lima',
    description: 'Entrena cara a cara con Andrea en Santa Anita, Lima.',
    includes: [
      '4 sesiones presenciales al mes (1 hora c/u)',
      'Evaluacion fisica inicial',
      'Plan de entrenamiento personalizado',
      'Seguimiento de progreso mensual',
      'Soporte por WhatsApp entre sesiones',
    ],
    popular: false,
    active: true,
  },
  {
    id: '5',
    name: 'Plan Nutricional',
    type: 'nutricion',
    price: 79,
    currency: 'USD',
    duration: 'Plan de 4 semanas',
    support_level: 'Soporte por WhatsApp',
    description: 'Plan de alimentacion personalizado segun tus objetivos.',
    includes: [
      'Evaluacion nutricional inicial',
      'Plan de alimentacion semanal personalizado',
      'Lista de compras detallada',
      'Recetas saludables',
      'Seguimiento quincenal',
      'Ajuste del plan al mes',
    ],
    popular: false,
    active: true,
  },
]

export const MOCK_CHALLENGES = [
  {
    id: '1',
    name: 'Reto 15 Dias',
    duration_days: 15,
    price: 29,
    currency: 'USD',
    description: 'Arranca tu transformacion en solo 15 dias con rutinas diarias.',
    includes: [
      '15 dias de rutinas en casa sin equipos',
      'Guia de alimentacion limpia',
      'Grupo de WhatsApp de apoyo',
      'Video de bienvenida de Andrea',
    ],
    active: true,
  },
  {
    id: '2',
    name: 'Reto 21 Dias',
    duration_days: 21,
    price: 39,
    currency: 'USD',
    description: 'Crea habitos saludables en 21 dias y nota el cambio real.',
    includes: [
      '21 dias de rutinas progresivas',
      'Plan de alimentacion completo',
      'Seguimiento de progreso semanal',
      'Grupo de WhatsApp de apoyo',
      'Recetario saludable PDF',
      'Check-in de resultados al final',
    ],
    active: true,
    popular: true,
  },
  {
    id: '3',
    name: 'Reto 30 Dias',
    duration_days: 30,
    price: 49,
    currency: 'USD',
    description: 'El reto definitivo para una transformacion completa en 30 dias.',
    includes: [
      '30 dias de rutinas progresivas e intensas',
      'Plan nutricional personalizado',
      'Video llamada de seguimiento a la mitad',
      'Grupo VIP de WhatsApp de apoyo',
      'Recetario saludable PDF',
      'Sesion de evaluacion final',
      'Certificado de reto completado',
    ],
    active: true,
  },
]

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Whey Protein Gold Standard',
    slug: 'whey-protein-gold-standard',
    category: 'proteinas',
    price: 89.9,
    currency: 'USD',
    stock: 15,
    brand: 'Optimum Nutrition',
    description: 'La proteina de suero mas vendida del mundo. 24g de proteina por servicio.',
    benefits: ['24g de proteina por servicio', 'Bajo en grasas y carbohidratos', 'Rapida absorcion post-entrenamiento'],
    usage_tips: 'Mezcla 1 scoop con 240ml de agua o leche. Consumir inmediatamente despues del entrenamiento.',
    status: 'available',
    images: ['/images/products/whey.jpg'],
  },
  {
    id: '2',
    name: 'Pre-Workout C4 Original',
    slug: 'pre-workout-c4-original',
    category: 'pre-entreno',
    price: 44.9,
    currency: 'USD',
    stock: 8,
    brand: 'Cellucor',
    description: 'El pre-entreno #1 en ventas. Energia, foco y rendimiento explosivo.',
    benefits: ['Energia sostenida sin crash', 'Mejora el foco mental', 'Pump muscular intenso'],
    usage_tips: 'Mezcla 1 scoop con 180ml de agua y consume 20-30 minutos antes del entrenamiento.',
    status: 'available',
    images: ['/images/products/c4.jpg'],
  },
  {
    id: '3',
    name: 'Creatina Monohidrato',
    slug: 'creatina-monohidrato',
    category: 'vitaminas',
    price: 24.9,
    currency: 'USD',
    stock: 20,
    brand: 'Optimum Nutrition',
    description: 'Creatina monohidrato pura micronizada para maxima fuerza y volumen muscular.',
    benefits: ['Aumenta la fuerza maxima', 'Mejora la recuperacion', 'Incrementa el volumen muscular'],
    usage_tips: '5g diarios. Puede tomarse antes o despues del entrenamiento.',
    status: 'available',
    images: ['/images/products/creatina.jpg'],
  },
  {
    id: '4',
    name: 'Multivitaminico Sport',
    slug: 'multivitaminico-sport',
    category: 'vitaminas',
    price: 19.9,
    currency: 'USD',
    stock: 25,
    brand: 'Now Sports',
    description: 'Formula completa de vitaminas y minerales para deportistas activos.',
    benefits: ['Soporte inmunologico', 'Mejora la recuperacion', 'Energia y vitalidad'],
    usage_tips: '1 capsula al dia con el desayuno.',
    status: 'available',
    images: ['/images/products/multi.jpg'],
  },
  {
    id: '5',
    name: 'Guantes de Entrenamiento Pro',
    slug: 'guantes-entrenamiento-pro',
    category: 'accesorios',
    price: 29.9,
    currency: 'USD',
    stock: 3,
    brand: 'Harbinger',
    description: 'Guantes profesionales con soporte de muneca para levantamiento de pesas.',
    benefits: ['Proteccion de manos', 'Soporte de muneca', 'Mayor agarre en la barra'],
    usage_tips: 'Selecciona tu talla correcta. Disponible en tallas S, M, L, XL.',
    status: 'available',
    images: ['/images/products/guantes.jpg'],
  },
  {
    id: '6',
    name: 'BCAA 2:1:1 Powder',
    slug: 'bcaa-211-powder',
    category: 'proteinas',
    price: 34.9,
    currency: 'USD',
    stock: 12,
    brand: 'Scitec Nutrition',
    description: 'Aminoacidos de cadena ramificada en proporcion 2:1:1 para recuperacion muscular.',
    benefits: ['Reduce el catabolismo muscular', 'Acelera la recuperacion', 'Disponible en varios sabores'],
    usage_tips: '1 scoop antes y despues del entrenamiento.',
    status: 'available',
    images: ['/images/products/bcaa.jpg'],
  },
]

export const MOCK_TESTIMONIALS = [
  {
    id: '1',
    client_name: 'Maria G.',
    goal: 'Perdida de grasa',
    quote: 'En 3 meses perdi 12kg y gane confianza que nunca habia tenido. Andrea no solo entrena tu cuerpo, entrena tu mente.',
    result: '-12kg en 3 meses',
  },
  {
    id: '2',
    client_name: 'Carlos M.',
    goal: 'Ganancia muscular',
    quote: 'Llevo 4 meses con el plan online y los resultados son increibles. Aumento de fuerza, mejor composicion corporal y energia todo el dia.',
    result: '+8kg masa muscular en 4 meses',
  },
  {
    id: '3',
    client_name: 'Lucia R.',
    goal: 'Tonificacion y fuerza',
    quote: 'Nunca pense que podria hacer sentadillas con 60kg de barra! Andrea me ensenio la tecnica correcta y ahora soy adicta al gym.',
    result: 'Fuerza x2 en 2 meses',
  },
  {
    id: '4',
    client_name: 'Diego P.',
    goal: 'Definicion muscular',
    quote: 'El plan nutricional fue clave. Por fin entiendo como alimentarme para rendir en el gym y al mismo tiempo definir. 100% recomendado.',
    result: '8% de grasa corporal en 3 meses',
  },
  {
    id: '5',
    client_name: 'Ana V.',
    goal: 'Post-parto y reconexion',
    quote: 'Despues de mi embarazo me sentia perdida. Andrea me ayudo a recuperar mi cuerpo y mi energia con mucha paciencia y profesionalismo.',
    result: 'Recuperacion completa en 4 meses',
  },
  {
    id: '6',
    client_name: 'Roberto S.',
    goal: 'Rendimiento deportivo',
    quote: 'Soy futbolista amateur y con Andrea mejore mi resistencia, velocidad y explosividad. Soy diferente en la cancha ahora.',
    result: 'Rendimiento +35% en 2 meses',
  },
]

export const MOCK_BLOG_POSTS = [
  {
    id: '1',
    title: '5 Errores Que Cometen Las Mujeres En El Gym (Y Como Evitarlos)',
    slug: '5-errores-mujeres-gym',
    category: 'mujeres',
    excerpt: 'Descubre los errores mas comunes que limitan tus resultados y aprende como corregirlos para transformar tu cuerpo mas rapido.',
    read_time: '5 min',
    cover_image: null,
    published: true,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    title: 'La Guia Definitiva de Proteinas Para Ganar Musculo',
    slug: 'guia-proteinas-ganar-musculo',
    category: 'suplementacion',
    excerpt: 'Todo lo que necesitas saber sobre las proteinas: cuanta necesitas, que tipo elegir y cuando tomarla para maximizar tus resultados.',
    read_time: '8 min',
    cover_image: null,
    published: true,
    created_at: '2024-01-10',
  },
  {
    id: '3',
    title: 'Rutina Full Body Para Principiantes (3 Dias a la Semana)',
    slug: 'rutina-full-body-principiantes',
    category: 'rutinas',
    excerpt: 'Esta rutina de 3 dias te dara resultados reales aunque seas principiante. Con videos explicativos y progresion garantizada.',
    read_time: '6 min',
    cover_image: null,
    published: true,
    created_at: '2024-01-05',
  },
  {
    id: '4',
    title: 'Como Perder Grasa Sin Perder Musculo: Guia Completa',
    slug: 'perder-grasa-sin-perder-musculo',
    category: 'nutricion',
    excerpt: 'El balance entre deficit calorico y entrenamiento de fuerza es la clave. Aprende la estrategia correcta para definir sin sacrificar musculo.',
    read_time: '10 min',
    cover_image: null,
    published: true,
    created_at: '2023-12-28',
  },
  {
    id: '5',
    title: 'Pre-Workout Natural vs Suplemento: Que Funciona Mejor?',
    slug: 'pre-workout-natural-vs-suplemento',
    category: 'suplementacion',
    excerpt: 'Cafe, platano o C4? Comparamos opciones naturales y suplementos para que decidas cual se adapta mejor a tu estilo de vida.',
    read_time: '7 min',
    cover_image: null,
    published: true,
    created_at: '2023-12-20',
  },
  {
    id: '6',
    title: 'Historia de Transformacion: De 0 A Fitness En 90 Dias',
    slug: 'historia-transformacion-90-dias',
    category: 'transformacion',
    excerpt: 'La historia real de Maria, quien nunca habia pisado un gym y en 90 dias logro el cuerpo que siempre quiso. Proceso, sacrificios y resultados.',
    read_time: '9 min',
    cover_image: null,
    published: true,
    created_at: '2023-12-15',
  },
]
